spring:
  application:
    name: spring-config-server
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trantrongdai/server-config
          search-paths: config-server/
server:
  port: 8888
management:
  security:
    enabled: false